#!/bin/sh
bspc rule -r "*"

remaps &
setbg &
xcompmgr &
unclutter &
sxhkd &
~/.config/polybar/launch.sh &
~/.config/screenlayout/default.sh &
xset r rate 300 50 &	
xsetroot -cursor_name left_ptr

bspc monitor HDMI-A-0       -d main music chat 4 5
bspc monitor DisplayPort-1  -d thrash 7 8 9 main

# bspc monitor HDMI-A-0       -d I II III IV V
# bspc monitor DisplayPort-1  -d VI VII VIII IX X

bspc config border_width            3
bspc config window_gap              0
bspc config top_padding             20	

bspc config split_ratio             0.52
bspc config automatic_scheme        spiral
bspc config focus_follows_pointer   true

bspc config pointer_modifer mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

start_bspwm

