#!/bin/sh
bspc rule -r "*"

startup &
sxhkd &
~/.config/polybar/launch.sh &

xset r rate 300 50 &	
xrdb ~/.config/colors/current.Xresources
xsetroot -cursor_name left_ptr

bspc monitor -d main-1 main-2 3 4 5 thrash 7 8 chat music

bspc config border_width            2
bspc config window_gap              0
bspc config top_padding             20

bspc config split_ratio             0.52
bspc config automatic_scheme        longest_side
bspc config focus_follows_pointer   true

bspc config pointer_modifer mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


# Border colors:
color_normal_border="#666666"
color_active_border="#666666"
color_focused_border="#ebcb8b"
color_presel_feedback="#888888"

bspc config normal_border_color $color_normal_border
bspc config active_border_color $color_active_border
bspc config focused_border_color $color_focused_border
bspc config presel_feedback_color $color_presel_feedback

start_bspwm

